"""
pipeline.py

This file is the orchestrator of the NUR RAG pipeline. It wires together every
component built in Phase 2 into the 5-step "Smart Archivist" flow defined in
docs/RAG_PIPELINE_ARCHITECTURE.md:

  Step 1 — Architect: Decompose the user query into 1..N sub-questions.
  Step 2 — Multi-Query Hybrid Retrieval: For each query (raw + sub-questions),
           run dense + sparse search across all 4 collections, fuse with RRF,
           deduplicate, keep top 30.
  Step 3 — (Phase 3: Reranker + Abstention Gate — not yet implemented)
  Step 4 — Reporter: Feed top 10 chunks to the LLM, get structured JSON report.
  Step 5 — (Phase 4: Post-Generation Verification — not yet implemented)

WHY THIS EXISTS:
  Without an orchestrator, the user would have to manually call the Architect,
  then encode the query, then call DenseRetriever, then SparseRetriever, then
  RRFFuser, then look up metadata, then render XML, then call the Reporter.
  That's 7 steps with complex data transformations between them. The pipeline
  encapsulates all of that into a single `query(user_question)` call.

LAZY LOADING:
  BGE-M3 is a 2.3GB model. We do NOT load it at construction time — we load it
  on the first `query()` call. This keeps the pipeline fast to instantiate
  (for testing/debugging) and avoids the model load if the user only wants to
  use the Architect or Reporter in isolation.

MULTI-QUERY DEDUPLICATION:
  The same chunk may appear in multiple query results (e.g., quran_2_222 might
  be found by both the raw user query and sub-question 1). We deduplicate by
  chunk ID, keeping the MAXIMUM RRF score across all (query, source) pairs.
  This rewards chunks that rank highly in at least one query without letting
  a chunk that ranks poorly everywhere inflate its score by appearing in many
  lists.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

import chromadb
from FlagEmbedding import BGEM3FlagModel

from src.nur.config import settings, CHROMA_PATH, SPARSE_PATH
from src.nur.generator import Generator, ReporterOutput
from src.nur.grades import (
    GRADE_INFO,
    WarningLevel,
    get_answer_warning,
    get_grade_info,
    normalize_grade_level,
)
from src.nur.retriever.dense import DenseRetriever
from src.nur.retriever.fusion import RRFFuser
from src.nur.retriever.reranker import CrossEncoderReranker
from src.nur.retriever.sparse import SparseRetriever
from src.nur.sources import SourceRef, render_sources_for_prompt


# ============================================================
# Result Dataclass — what the pipeline returns
# ============================================================


@dataclass
class PipelineResult:
    """The complete output of a NUR pipeline run.

    Contains both the final answer AND the intermediate steps, so the CLI
    (or any other consumer) can display a rich, transparent response showing
    exactly how the answer was derived.
    """

    user_query: str
    """The original question the user asked."""

    sub_questions: list[str] = field(default_factory=list)
    """The 1..N sub-questions generated by the Architect (Step 1)."""

    search_keywords: list[str] = field(default_factory=list)
    """The 5..15 search keywords extracted by the Architect (DEC-032).
    These are used as additional retrieval queries to improve recall.
    LLM-driven query expansion — NOT hardcoded synonyms."""

    retrieved_chunks: list[dict[str, Any]] = field(default_factory=list)
    """The pool of chunks after multi-query hybrid retrieval + RRF fusion
    (Step 2). Size = top_k_initial (100 in Phase 3). Each dict has: id,
    rrf_score, source, dense_rank, sparse_rank."""

    reranked_chunks: list[dict[str, Any]] = field(default_factory=list)
    """The top-K chunks after cross-encoder reranking (Step 3). Each dict has:
    id, source, reranker_score, authenticity_weight, final_score, rrf_score,
    rrf_rank. Sorted by final_score descending."""

    abstained: bool = False
    """True if the pipeline abstained from answering (Pillar 4). This happens
    when the top-1 reranker score < 0.35 — the cross-encoder is not confident
    that any retrieved chunk actually answers the question. In this case,
    `report` is None and the CLI shows 'Insufficient sources'."""

    top_chunks: list[SourceRef] = field(default_factory=list)
    """The top 10 chunks (after reranking) converted to SourceRef objects and
    rendered as XML for the Reporter (Step 4)."""

    report: ReporterOutput | None = None
    """The final structured JSON report from the Reporter (Step 4). None if
    the pipeline failed before generation OR if it abstained."""

    answer_warning: str | None = None
    """The answer-level warning computed from the hadith grades in the report
    (Step 4 post-processing). Implements the two-tier warning logic from
    src/nur/grades.py: CRITICAL if any Mawdu', BIG if only Da'if (no
    Sahih/Hasan), SMALL if Da'if alongside Sahih/Hasan, NONE otherwise.
    This is a Pillar 4 post-generation enrichment — the grade comes from the
    metadata, NOT from the LLM."""

    grade_explanations: dict[str, str] = field(default_factory=dict)
    """A map of source_id → plain-language grade explanation, for each hadith
    cited in the report. The CLI displays this so users understand what
    'Sahih', 'Hasan', 'Da'if', 'Mawdu' mean. Quran and Tafsir sources are
    excluded (they don't have grades)."""

    error: str | None = None
    """If the pipeline failed, the error message. None on success."""


# ============================================================
# The Pipeline
# ============================================================


class NURPipeline:
    """Orchestrates the full NUR RAG pipeline: Architect → Retrieval → Reporter.

    This is the main entry point for the CLI (and any future API server).
    Instantiate once, then call `query()` for each user question.
    """

    # The 4 collections to search for every query.
    # Per docs/RAG_PIPELINE_ARCHITECTURE.md Step 2: "searches the 4 separate
    # indexes (Quran, Hadith, Tafsir, Scholar)". Tafsir is split into AR + EN
    # in our database, so we search 4 collections. The Scholar index is a
    # Phase 5 addition and is not yet present.
    SOURCES = ["quran", "hadith", "tafsir_ar", "tafsir_en"]

    def __init__(
        self,
        db_path: str = str(CHROMA_PATH),
        sparse_path: str = str(SPARSE_PATH),
        device: str | None = None,
    ) -> None:
        """Initialize the pipeline with all its components.

        BGE-M3 is NOT loaded here — it's lazy-loaded on the first query() call
        to keep construction fast.

        Args:
            db_path: Path to the ChromaDB directory.
            sparse_path: Path to the sparse JSON index directory.
            device: Device for BGE-M3 ('mps', 'cuda', 'cpu'). If None,
                    auto-detects the best available device.
        """
        # Retrieval components (lightweight — load instantly)
        self.dense_retriever = DenseRetriever(db_path=db_path)
        self.sparse_retriever = SparseRetriever(sparse_path=sparse_path)
        self.fuser = RRFFuser()

        # Reranker (lazy-loaded on first query — 568M params, ~1.2GB)
        self.reranker = CrossEncoderReranker(device=device)

        # Generator (Architect + Reporter — lightweight, no model loaded yet)
        self.generator = Generator()

        # ChromaDB client for metadata lookups (to build SourceRef objects)
        self._chroma_client = chromadb.PersistentClient(path=db_path)
        self._collections_cache: dict[str, Any] = {}

        # BGE-M3 (lazy-loaded on first query)
        self._model: BGEM3FlagModel | None = None
        self._device = device or self._auto_detect_device()

    @staticmethod
    def _auto_detect_device() -> str:
        """Pick the best available device for BGE-M3 inference.

        Priority: CUDA (NVIDIA) > MPS (Apple Silicon) > CPU.
        """
        import torch

        if torch.cuda.is_available():
            return "cuda"
        if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
            return "mps"
        return "cpu"

    @property
    def model(self) -> BGEM3FlagModel:
        """Lazily load and cache the BGE-M3 model on first access.

        Loading takes ~10 seconds (2.3GB weights from local cache).
        Subsequent accesses return the cached instance.
        """
        if self._model is None:
            print(f"Loading BGE-M3 on {self._device}...")
            self._model = BGEM3FlagModel(
                settings.embedding_model,
                use_fp16=True,
                devices=self._device,
            )
            print("✅ BGE-M3 loaded.")
        return self._model

    def _get_collection(self, source: str):
        """Get a ChromaDB collection by source name, with caching.

        Args:
            source: One of 'quran', 'hadith', 'tafsir_ar', 'tafsir_en'.

        Returns:
            The ChromaDB collection object.
        """
        if source not in self._collections_cache:
            col_name = f"{source}_dense"
            self._collections_cache[source] = self._chroma_client.get_collection(col_name)
        return self._collections_cache[source]

    def _encode_query(self, query: str) -> tuple[list[float], dict[int, float]]:
        """Encode a user query into dense + sparse vectors using BGE-M3.

        Args:
            query: The user's question string (any language: EN/FR/AR).

        Returns:
            A tuple of (dense_vector, sparse_vector) where:
              - dense_vector is a list of 1024 floats
              - sparse_vector is a dict {token_id: weight}
        """
        output = self.model.encode(
            [query],
            return_dense=True,
            return_sparse=True,
            return_colbert_vecs=False,
        )

        # Dense vector: tensor → numpy → list
        dense_vec = output["dense_vecs"][0]
        if hasattr(dense_vec, "cpu"):
            dense_vec = dense_vec.cpu().numpy()
        dense_list = dense_vec.tolist()

        # Sparse vector: dict of {token_id: weight} — normalize keys to int
        sparse_raw = output["lexical_weights"][0]
        sparse_dict = {int(k): float(v) for k, v in sparse_raw.items()}

        return dense_list, sparse_dict

    def _retrieve(
        self,
        queries: list[str],
        top_k: int = settings.top_k_initial,
    ) -> list[dict[str, Any]]:
        """Run multi-query hybrid retrieval across all 4 collections (Step 2).

        For each query:
          1. Encode it ONCE with BGE-M3 (dense + sparse in one call).
          2. For each of the 4 sources:
             a. Run DenseRetriever.search() → top 30 dense results
             b. Run SparseRetriever.search() → top 30 sparse results
             c. Fuse with RRFFuser → top 30 fused results
          3. Collect all fused results across all (query, source) pairs.

        Then deduplicate by chunk ID (keeping the max RRF score) and return
        the top_k overall.

        Args:
            queries: List of query strings (raw user query + sub-questions).
            top_k: Number of chunks to return after dedup + sorting.

        Returns:
            A list of dicts, each with: id, rrf_score, source, dense_rank,
            sparse_rank. Sorted by rrf_score descending.
        """
        # Pool of all fused results across all (query, source) pairs.
        # Keyed by chunk_id to deduplicate. We keep the MAX rrf_score.
        pool: dict[str, dict[str, Any]] = {}

        for query_idx, query in enumerate(queries):
            # Encode this query ONCE — reuse the vectors for all 4 sources
            dense_vec, sparse_vec = self._encode_query(query)
            query_label = "raw" if query_idx == 0 else f"sub{query_idx}"
            print(f"  [{query_label}] Encoded query ({len(sparse_vec)} sparse tokens)")

            for source in self.SOURCES:
                # Dense search — use top_k (the pool size), not hardcoded 30
                dense_results = self.dense_retriever.search(
                    query_vector=dense_vec, source=source, top_k=top_k
                )
                # Sparse search
                sparse_results = self.sparse_retriever.search(
                    query_sparse=sparse_vec, source=source, top_k=top_k
                )
                # RRF fusion
                fused = self.fuser.fuse(
                    dense_results=dense_results,
                    sparse_results=sparse_results,
                    top_k=top_k,
                )

                # Merge into the global pool (keep max rrf_score per chunk)
                for item in fused:
                    cid = item["id"]
                    if cid not in pool or item["rrf_score"] > pool[cid]["rrf_score"]:
                        pool[cid] = {
                            "id": cid,
                            "rrf_score": item["rrf_score"],
                            "source": source,
                            "dense_rank": item["dense_rank"],
                            "sparse_rank": item["sparse_rank"],
                        }

        # Sort by rrf_score descending and truncate
        sorted_results = sorted(pool.values(), key=lambda x: -x["rrf_score"])
        return sorted_results[:top_k]

    def _chunks_to_source_refs(self, chunks: list[dict[str, Any]]) -> list[SourceRef]:
        """Convert fused chunk results into SourceRef objects for the LLM prompt.

        Fetches each chunk's metadata from ChromaDB and constructs a SourceRef
        with the appropriate fields for its source type (quran, hadith,
        tafsir_ar, tafsir_en).

        Args:
            chunks: List of fused result dicts (must have 'id' and 'source').

        Returns:
            List of SourceRef objects, in the same order as the input chunks.
        """
        # Group chunk IDs by source so we can batch-fetch metadata per collection
        by_source: dict[str, list[str]] = {}
        for chunk in chunks:
            by_source.setdefault(chunk["source"], []).append(chunk["id"])

        # Fetch metadata for each source's chunks in one batch
        metadata_map: dict[str, dict[str, Any]] = {}
        for source, chunk_ids in by_source.items():
            collection = self._get_collection(source)
            res = collection.get(ids=chunk_ids, include=["metadatas", "documents"])
            for i, cid in enumerate(res["ids"]):
                metadata_map[cid] = {
                    "metadata": res["metadatas"][i],
                    "document": res["documents"][i],
                    "source": source,
                }

        # Build SourceRef objects in the same order as the input chunks
        source_refs: list[SourceRef] = []
        for chunk in chunks:
            cid = chunk["id"]
            info = metadata_map.get(cid)
            if not info:
                # Chunk not found in ChromaDB — skip it (shouldn't happen)
                continue
            source_ref = self._build_source_ref(cid, info["metadata"], info["source"])
            source_refs.append(source_ref)

        return source_refs

    def _fetch_chunk_documents(
        self,
        chunks: list[dict[str, Any]],
    ) -> list[dict[str, Any]]:
        """Fetch the full document text for each chunk from ChromaDB.

        The reranker needs the actual chunk text to score [query, chunk] pairs.
        ChromaDB stores the document text separately from the metadata, so we
        batch-fetch it here.

        Args:
            chunks: List of chunk dicts from the retriever. Each must have
                    'id' and 'source'.

        Returns:
            The same list of chunk dicts, each augmented with a 'document' key
            containing the full chunk text (including the bilingual context
            prefix from Phase 1).
        """
        # Group chunk IDs by source for batch fetching
        by_source: dict[str, list[str]] = {}
        for chunk in chunks:
            by_source.setdefault(chunk["source"], []).append(chunk["id"])

        # Fetch documents for each source's chunks in one batch
        doc_map: dict[str, str] = {}
        for source, chunk_ids in by_source.items():
            collection = self._get_collection(source)
            res = collection.get(ids=chunk_ids, include=["documents"])
            for i, cid in enumerate(res["ids"]):
                doc_map[cid] = res["documents"][i] if i < len(res["documents"]) else ""

        # Augment the input chunks with the 'document' field
        result: list[dict[str, Any]] = []
        for chunk in chunks:
            chunk_copy = dict(chunk)
            chunk_copy["document"] = doc_map.get(chunk["id"], "")
            result.append(chunk_copy)

        return result

    @staticmethod
    def _build_source_ref(chunk_id: str, metadata: dict[str, Any], source: str) -> SourceRef:
        """Build a SourceRef from ChromaDB metadata, handling all 4 source types.

        Each source type has a different metadata schema:
          - quran:     text_ar, text_en, surah_num, ayah_num, url
          - hadith:    text_ar, text_en, collection, hadith_number, grade, url
          - tafsir_ar: tafsir_text_ar, surah_num, ayah_num, url
          - tafsir_en: tafsir_text, surah_num, ayah_num, url

        Args:
            chunk_id: The chunk ID (e.g. 'quran_1_1').
            metadata: The chunk's metadata dict from ChromaDB.
            source: The source type ('quran', 'hadith', 'tafsir_ar', 'tafsir_en').

        Returns:
            A populated SourceRef object.
        """
        if source == "quran":
            return SourceRef(
                kind="quran",
                surah=metadata.get("surah_num"),
                ayah=metadata.get("ayah_num"),
                text_ar=metadata.get("text_ar", ""),
                text_en=metadata.get("text_en", ""),
            )
        if source == "hadith":
            return SourceRef(
                kind="hadith",
                collection=metadata.get("collection"),
                hadith_number=metadata.get("hadith_number"),
                text_ar=metadata.get("text_ar", ""),
                text_en=metadata.get("text_en", ""),
                grade=metadata.get("grade"),
            )
        if source == "tafsir_ar":
            # Tafsir AR: the "Arabic text" is the tafsir commentary itself
            return SourceRef(
                kind="tafsir_ar",
                surah=metadata.get("surah_num"),
                ayah=metadata.get("ayah_num"),
                text_ar=metadata.get("tafsir_text_ar", ""),
                text_en="",
            )
        if source == "tafsir_en":
            # Tafsir EN: English translation of the tafsir
            return SourceRef(
                kind="tafsir_en",
                surah=metadata.get("surah_num"),
                ayah=metadata.get("ayah_num"),
                text_ar="",
                text_en=metadata.get("tafsir_text", ""),
            )
        # Should never reach here
        raise ValueError(f"Unknown source type: {source}")

    def _enrich_report_with_grades(self, result: PipelineResult) -> PipelineResult:
        """Attach grade info to each direct_report and compute the answer warning.

        This is a Pillar 4 (Post-Generation Verification) enrichment step. The
        Reporter LLM generates direct_reports with source_id, source_type,
        arabic_text, and report — but NOT the grade. We attach the grade
        AFTER generation, looking it up from the SourceRef metadata that was
        injected into the prompt. This prevents the LLM from hallucinating or
        misreading grades.

        Also computes the answer-level warning using the two-tier logic from
        src/nur/grades.py:
          - CRITICAL if any Mawdu' (fabricated) hadith is cited.
          - BIG if only Da'if hadiths are cited (no Sahih/Hasan).
          - SMALL if Da'if is cited alongside Sahih/Hasan.
          - NONE if only Sahih/Hasan (or no hadiths at all).

        Args:
            result: The PipelineResult after Step 4 (report generated).

        Returns:
            The same PipelineResult with `answer_warning` and
            `grade_explanations` populated.
        """
        if not result.report or not result.top_chunks:
            return result

        # Build a map of source_id (S1, S2, ...) → SourceRef for quick lookup
        source_map: dict[str, SourceRef] = {
            f"S{i+1}": ref for i, ref in enumerate(result.top_chunks)
        }

        # Collect grade levels for all HADITH sources cited in the report
        # (Quran and Tafsir don't have grades — they're excluded from the
        # answer-warning calculation)
        hadith_grade_levels: list[str] = []

        for direct_report in result.report.direct_reports:
            ref = source_map.get(direct_report.source_id)
            if not ref:
                continue

            # Only hadiths have grades. Quran = Word of Allah, Tafsir = commentary.
            if ref.kind == "hadith" and ref.grade:
                grade_info = get_grade_info(ref.grade)
                level = grade_info["level"]

                # Store the explanation for the CLI to display
                result.grade_explanations[direct_report.source_id] = (
                    f"{grade_info['label']} — {grade_info['explanation']}"
                )

                hadith_grade_levels.append(level)

                # Attach the grade level to the direct_report for downstream use
                # (the CLI can read direct_report.grade_level if it wants)
                # Note: we can't modify the Pydantic model's fields here because
                # grade/grade_level aren't defined on DirectReport. The
                # grade_explanations dict on PipelineResult is the canonical
                # place for this info. Phase 4 will add formal fields to
                # DirectReport when we implement the verification schema.

        # Compute the answer-level warning from the collected hadith grades
        warning_level, warning_text = get_answer_warning(hadith_grade_levels)
        result.answer_warning = warning_text

        return result

    def query(
        self,
        user_query: str,
        force_reasoning: bool = False,
    ) -> PipelineResult:
        """Run the full NUR pipeline on a user question.

        Executes the 5-step Smart Archivist pipeline:
          Step 1: Architect — decompose query into sub-questions + extract keywords
          Step 2: Multi-query hybrid retrieval (raw + sub-questions + keywords)
          Step 3: Cross-encoder reranking + abstention gate
          Step 4: Reporter — structured JSON generation
          Step 4b: Grade enrichment (post-generation)
          Step 5: (Phase 4 — verification, not yet implemented)

        Args:
            user_query: The user's question, in any language (EN/FR/AR).
            force_reasoning: If True, use the Llama 3.3 70B reasoning model
                             instead of the default Scout. Use only for extreme
                             Ikhtilaf cases.

        Returns:
            A PipelineResult with all intermediate data. If the pipeline
            abstained (top-1 reranker score < 0.35), `abstained` is True and
            `report` is None. If any step failed, `error` is set.
        """
        result = PipelineResult(user_query=user_query)

        try:
            # ── Step 1: Architect — Query Decomposition + Keyword Extraction ──
            print(f"\n📝 Step 1: Architect decomposing query + extracting keywords...")
            result.sub_questions, result.search_keywords = self.generator.decompose_query(user_query)

            # All queries for retrieval: raw + sub-questions + keywords
            # Keywords are the user's idea (DEC-032) — LLM-driven query expansion
            # that works for any topic without hardcoded synonym tables.
            all_queries = [user_query] + result.sub_questions + result.search_keywords

            print(f"   Generated {len(result.sub_questions)} sub-questions:")
            for i, sq in enumerate(result.sub_questions, 1):
                print(f"     {i}. {sq}")
            print(f"   Extracted {len(result.search_keywords)} search keywords:")
            print(f"     {', '.join(result.search_keywords)}")

            # ── Step 2: Multi-Query Hybrid Retrieval ──
            print(f"\n🔍 Step 2: Retrieving from {len(self.SOURCES)} collections × {len(all_queries)} queries...")
            result.retrieved_chunks = self._retrieve(all_queries, top_k=settings.top_k_initial)
            print(f"   Retrieved {len(result.retrieved_chunks)} unique chunks (pool size: {settings.top_k_initial}).")

            # ── Step 3: Cross-Encoder Reranking + Abstention Gate ──
            print(f"\n🎯 Step 3: Reranking {len(result.retrieved_chunks)} chunks with cross-encoder...")

            # Fetch chunk documents (text) from ChromaDB for the reranker.
            # The reranker needs the actual text to score [query, chunk] pairs.
            chunks_with_docs = self._fetch_chunk_documents(result.retrieved_chunks)

            # Build SourceRefs for ALL retrieved chunks (needed for authenticity weighting)
            all_source_refs = self._chunks_to_source_refs(result.retrieved_chunks)

            # Rerank: score all chunks, apply authenticity weighting, keep top-K
            result.reranked_chunks = self.reranker.rerank(
                query=user_query,
                chunks=chunks_with_docs,
                source_refs=all_source_refs,
                top_k=settings.top_k_rerank,
                apply_authenticity_weight=True,
                normalize=True,
            )

            # Print the top-5 reranker scores for transparency
            print(f"   Top 5 reranker scores:")
            for i, chunk in enumerate(result.reranked_chunks[:5], 1):
                print(f"     {i}. {chunk['id']:30s} reranker={chunk['reranker_score']:.4f} "
                      f"weight={chunk['authenticity_weight']:.2f} final={chunk['final_score']:.4f}")

            # ── Step 3b: Abstention Gate (Pillar 4) ──
            # If the top-1 reranker score < 0.35, the cross-encoder is not
            # confident that any chunk answers the question. We ABSTAIN rather
            # than generate a potentially-misleading answer from weak sources.
            if self.reranker.should_abstain(result.reranked_chunks, threshold=0.35):
                top_score = result.reranked_chunks[0]["reranker_score"] if result.reranked_chunks else 0.0
                result.abstained = True
                print(f"\n🚫 Step 3b: ABSTENTION — top reranker score {top_score:.4f} < 0.35 threshold.")
                print(f"   The system does not have sufficient reliable sources to answer this question.")
                return result

            print(f"\n✅ Step 3b: Top score {result.reranked_chunks[0]['reranker_score']:.4f} >= 0.35 — proceeding to generation.")

            # Convert the top-K reranked chunks to SourceRef objects for the Reporter.
            # We re-fetch SourceRefs for just the top-K (the reranked order may differ
            # from the RRF order).
            top_chunk_dicts = []
            for rc in result.reranked_chunks:
                # Find the original retrieved chunk dict by ID
                for orig in result.retrieved_chunks:
                    if orig["id"] == rc["id"]:
                        top_chunk_dicts.append(orig)
                        break
            result.top_chunks = self._chunks_to_source_refs(top_chunk_dicts)
            print(f"   {len(result.top_chunks)} SourceRef objects built for the Reporter.")

            # ── Step 4: Reporter — Structured Generation ──
            print(f"\n🎙️ Step 4: Reporter generating structured report...")
            sources_xml = render_sources_for_prompt(result.top_chunks)
            result.report = self.generator.generate_report(
                user_query=user_query,
                sources_xml=sources_xml,
                force_reasoning=force_reasoning,
            )
            print(f"   ✅ Report generated with {len(result.report.direct_reports)} direct reports.")

            # ── Step 4b: Grade Enrichment (Pillar 3 + Pillar 4) ──
            # Attach grade info to each direct_report and compute the
            # answer-level warning. This is post-generation enrichment — we
            # use the actual metadata, NOT the LLM's copy of the grade.
            # This prevents the LLM from hallucinating or misreading grades.
            result = self._enrich_report_with_grades(result)
            if result.answer_warning:
                print(f"   ⚠️ Answer warning: {result.answer_warning[:80]}...")

            # ── Step 5: (Phase 4 — Post-Generation Verification goes here) ──
            # TODO Phase 4: NLI verification + Arabic character matching

        except Exception as e:
            result.error = f"{type(e).__name__}: {e}"
            print(f"\n❌ Pipeline error: {result.error}")

        return result
